### **1. Importing Libraries**

In [1]:
import pandas as pd
import numpy as np

### **2. Importing Data**

In [2]:
df = pd.read_json("datasets/CLEANED_videos_count_data.json")

In [3]:
df = df.T

In [4]:
display(df)

,id,title,kind,viewCount,likeCount,commentCount,date,time,artist
0,YudHcBIxlYw,JISOO - ‘꽃(FLOWER)’ M\/V,Music Video,390657394,10117824,1340919,2023-09-19,17:01:02.392672,JISOO
1,POe9SOEKotk,BLACKPINK - ‘Shut Down’ M\/V,Music Video,522252772,10824498,2239017,2023-09-19,17:01:02.392707,BLACKPINK
2,gQlMMD8auMs,BLACKPINK - ‘Pink Venom’ M\/V,Music Video,731994719,16069895,3569773,2023-09-19,17:01:02.392717,BLACKPINK
3,awkkyBH2zEo,LISA - 'LALISA' M\/V,Music Video,653808793,17313679,2815724,2023-09-19,17:01:02.392725,LISA
4,K9_VFxzCuQ0,ROSÉ - 'Gone' M\/V,Music Video,267505076,7376149,1240229,2023-09-19,17:01:02.392734,ROSÉ
...,...,...,...,...,...,...,...,...,...
104610,EKHdMwRaU60,BLACKPINK​ - '붐바야(BOOMBAYAH)' 0828 SBS Inkigayo,Performance,61728639,831878,23032,2026-04-09,02:36:06.528090,BLACKPINK
104611,metZ_f8aqC0,BLACKPINK​ - '휘파람(WHISTLE)' 0821 SBS Inkigayo,Performance,46304222,930684,27322,2026-04-09,02:36:06.528093,BLACKPINK
104612,RGmL76BBGZk,BLACKPINK​ - '붐바야(BOOMBAYAH)' 0821 SBS Inkigay...,Performance,17935135,559038,15435,2026-04-09,02:36:06.528095,BLACKPINK
104613,vAqAp1tJnkc,BLACKPINK - '휘파람’(WHISTLE) 0814 SBS Inkigayo,Performance,49598712,874725,29521,2026-04-09,02:36:06.528097,BLACKPINK
104614,LpSH8MrYCfg,BLACKPINK - '붐바야(BOOMBAYAH)' 0814 SBS Inkigayo,Performance,190739022,2678814,82396,2026-04-09,02:36:06.528099,BLACKPINK

### **3. Data Information**

#### **Data dimensions**:

In [5]:
df.shape

(104615, 9)

#### **Details for each row:**

The information of one video, including id, title, artist, views, likes,...

In [6]:
df.head(1)

,id,title,kind,viewCount,likeCount,commentCount,date,time,artist
0,YudHcBIxlYw,JISOO - ‘꽃(FLOWER)’ M\/V,Music Video,390657394,10117824,1340919,2023-09-19,17:01:02.392672,JISOO

#### **Details for each column:**

| Column       | Description                                                                                     |
|--------------|-------------------------------------------------------------------------------------------------|
| id           | The unique identifier for the video on YouTube.                                                 |
| title        | The title of the video.                                                                         |
| kind         | The type or category of the video content.                                                      |
| viewCount    | The total number of views the video has received on YouTube.                                     |
| likeCount    | The total number of likes the video has received on YouTube.                                     |
| commentCount | The total number of comments posted on the video on YouTube.                                     |
| date         | The date when the data was collected or the statistics were obtained.                            |
| time         | The time when the data was collected or the statistics were obtained (if applicable).            |
| artist       | The artist or creator associated with the video content.                                         |

#### **Data types of each column:**

In [7]:
df.dtypes

id              object
title           object
kind            object
viewCount       object
likeCount       object
commentCount    object
date            object
time            object
artist          object
dtype: object

Convert the `viewCount`, `likeCount`, `commentCount` to int:

In [8]:
df['viewCount'] = df['viewCount'].astype(np.int64)
df['likeCount'] = df['likeCount'].astype(np.int64)
df['commentCount'] = df['commentCount'].astype(np.int64)

Convert the `date` column to datetime type:

In [9]:
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')

In [10]:
#df['time'] = pd.to_datetime(df['time'], format='%H:%M:%S.%f').dt.time

#### **Number of missing values in each column:**

In [11]:
df.isnull().sum()

id              0
title           0
kind            0
viewCount       0
likeCount       0
commentCount    0
date            0
time            0
artist          0
dtype: int64

#### **Investigating missing data days**

In [12]:
all_dates = pd.date_range(start=df['date'].min(), end=df['date'].max(), freq='D')
missing_dates = all_dates[~all_dates.isin(df['date'])]
print("Missing dates:")
if len(missing_dates) > 0:
    print(missing_dates)

Missing dates:
DatetimeIndex(['2024-06-17', '2024-06-18', '2024-06-19', '2024-06-20',
               '2024-06-21', '2024-06-22', '2024-06-23', '2024-06-24',
               '2024-06-25', '2024-06-26', '2024-06-27', '2024-06-28',
               '2024-06-29', '2024-06-30', '2024-07-01', '2024-07-02',
               '2024-07-03', '2024-07-04', '2024-07-05', '2024-07-06',
               '2024-07-07', '2024-07-08', '2024-07-09', '2024-07-10',
               '2024-07-11', '2024-07-12', '2024-07-13', '2024-07-14',
               '2024-07-15', '2024-07-16', '2024-07-17', '2024-07-18',
               '2024-07-19', '2024-07-20', '2024-07-21', '2024-07-22',
               '2024-07-23', '2024-07-24', '2024-07-25', '2024-07-26',
               '2024-07-27', '2024-07-28', '2024-07-29', '2024-07-30',
               '2024-07-31', '2024-08-01', '2024-08-02', '2024-08-03',
               '2024-08-04', '2024-08-05', '2024-08-06', '2024-08-07',
               '2024-08-08', '2024-08-09', '2024-08-10', '2024-08-11',
               '2024-08-12', '2024-08-13', '2024-08-14', '2024-08-15',
               '2024-08-16', '2024-08-17', '2024-08-18', '2024-08-19',
               '2024-08-20', '2024-08-21', '2024-08-22', '2024-08-23',
               '2024-08-24', '2024-08-25', '2024-08-26', '2024-08-27',
               '2024-08-28', '2024-08-29', '2024-08-30', '2024-08-31',
               '2024-09-01', '2024-09-02', '2024-09-03', '2024-09-04',
               '2024-12-18'],
              dtype='datetime64[ns]', freq=None)

#### **Date of First Data Collection? Date of Last Data Collection?**

In [13]:
print("Date of First Data Collection:", df['date'].dt.date.min())
print("Date of Last Data Collection:", df['date'].dt.date.max())

Date of First Data Collection: 2023-09-19
Date of Last Data Collection: 2026-04-09

#### **The number of distinct videos in the dataset:**

In [14]:
df.id.nunique()

125

#### **Number of videos for each video types:**

In [15]:
kind_video_counts = df.drop_duplicates(subset=['kind', 'id']).groupby('kind').size().reset_index(name='count').sort_values(by='count',ascending=False)
kind_video_counts['percentage'] = round(kind_video_counts['count'] / kind_video_counts['count'].sum() * 100,2)
display(kind_video_counts)

                   kind  count  percentage
2           Performance     88       69.29
0  Dance Practice Video     20       15.75
1           Music Video     19       14.96

#### **Number of videos for each artist:**

In [16]:
artist_video_counts = df.drop_duplicates(subset=['artist', 'id']).groupby('artist').size().reset_index(name='count').sort_values(by='count',ascending=False)
artist_video_counts['percentage'] = round(artist_video_counts['count'] / artist_video_counts['count'].sum() * 100,2)
display(artist_video_counts)

      artist  count  percentage
0  BLACKPINK     98        78.4
1     JENNIE     11         8.8
4       ROSÉ      8         6.4
3       LISA      6         4.8
2      JISOO      2         1.6

In [17]:
artist_video_counts_2 = df.drop_duplicates(subset=['artist','id','kind']).groupby(['artist','kind']).size().reset_index(name='count').sort_values(by=['count'],ascending=False).sort_values(by=['artist'])
display(artist_video_counts_2)

       artist                  kind  count
2   BLACKPINK           Performance     72
1   BLACKPINK           Music Video     14
0   BLACKPINK  Dance Practice Video     12
5      JENNIE           Performance      6
3      JENNIE  Dance Practice Video      4
4      JENNIE           Music Video      1
6       JISOO  Dance Practice Video      1
7       JISOO           Music Video      1
8       JISOO           Performance      1
11       LISA           Performance      3
9        LISA  Dance Practice Video      2
10       LISA           Music Video      1
14       ROSÉ           Performance      6
13       ROSÉ           Music Video      2
12       ROSÉ  Dance Practice Video      1

#### **Most Viewed Video by Each Video types:**

In [18]:
most_viewed_videos = df.loc[df.groupby('kind')['viewCount'].idxmax()].reset_index()
most_viewed_videos['link'] = f'https://www.youtube.com/watch?v=' + most_viewed_videos['id']
print("Most Viewed Video by Each Video types:")
display(most_viewed_videos[['kind', 'title', 'viewCount','link']])

Most Viewed Video by Each Video types:

,kind,title,viewCount,link
0,Dance Practice Video,BLACKPINK - 'How You Like That' DANCE PERFORMA...,1979833234,https://www.youtube.com/watch?v=32si5cfrCNc
1,Music Video,BLACKPINK - ‘뚜두뚜두 (DDU-DU DDU-DU)’ M\/V,2380623358,https://www.youtube.com/watch?v=IHNzOHi8sJs
2,Performance,LISA - 'MONEY' EXCLUSIVE PERFORMANCE VIDEO,1202262949,https://www.youtube.com/watch?v=dNCWe_6HAM8

#### **Most Viewed Video by Each Artist**

In [19]:
most_viewed_videos = df.loc[df.groupby('artist')['viewCount'].idxmax()].reset_index()
most_viewed_videos['link'] = f'https://www.youtube.com/watch?v=' + most_viewed_videos['id']
print("Most Viewed Video by Each Artist:")
display(most_viewed_videos[['artist', 'title', 'viewCount','link']])

Most Viewed Video by Each Artist:

,artist,title,viewCount,link
0,BLACKPINK,BLACKPINK - ‘뚜두뚜두 (DDU-DU DDU-DU)’ M\/V,2380623358,https://www.youtube.com/watch?v=IHNzOHi8sJs
1,JENNIE,JENNIE - 'SOLO' M\/V,1079983207,https://www.youtube.com/watch?v=b73BI9eUkjM
2,JISOO,JISOO - ‘꽃(FLOWER)’ M\/V,641968270,https://www.youtube.com/watch?v=YudHcBIxlYw
3,LISA,LISA - 'MONEY' EXCLUSIVE PERFORMANCE VIDEO,1202262949,https://www.youtube.com/watch?v=dNCWe_6HAM8
4,ROSÉ,ROSÉ - 'On The Ground' M\/V,390472517,https://www.youtube.com/watch?v=CKZvWhCqx1s

#### **Top 10 Videos with the Highest Number of Views**

In [20]:
latest_view_per_video = df.drop_duplicates(subset='id', keep='last')
top_10_viewed_videos = latest_view_per_video.nlargest(10, 'viewCount').reset_index()
top_10_viewed_videos['link'] = f'https://www.youtube.com/watch?v=' + top_10_viewed_videos['id']
print("Top 10 Videos with the Highest Number of Views:")
display(top_10_viewed_videos[['title', 'kind','artist','viewCount','link']])

Top 10 Videos with the Highest Number of Views:

,title,kind,artist,viewCount,link
0,BLACKPINK - ‘뚜두뚜두 (DDU-DU DDU-DU)’ M\/V,Music Video,BLACKPINK,2380623358,https://www.youtube.com/watch?v=IHNzOHi8sJs
1,BLACKPINK - 'Kill This Love' M\/V,Music Video,BLACKPINK,2200051175,https://www.youtube.com/watch?v=2S24-y0Ij3Y
2,BLACKPINK - 'How You Like That' DANCE PERFORMA...,Dance Practice Video,BLACKPINK,1979833234,https://www.youtube.com/watch?v=32si5cfrCNc
3,BLACKPINK - '붐바야 (BOOMBAYAH)' M\/V,Music Video,BLACKPINK,1866736665,https://www.youtube.com/watch?v=bwmSjveL3Lc
4,BLACKPINK - '마지막처럼 (AS IF IT'S YOUR LAST)' M\/V,Music Video,BLACKPINK,1512166696,https://www.youtube.com/watch?v=Amq-qlqbjYA
5,BLACKPINK - 'How You Like That' M\/V,Music Video,BLACKPINK,1366587818,https://www.youtube.com/watch?v=ioNng23DkIM
6,LISA - 'MONEY' EXCLUSIVE PERFORMANCE VIDEO,Performance,LISA,1202262949,https://www.youtube.com/watch?v=dNCWe_6HAM8
7,JENNIE - 'SOLO' M\/V,Music Video,JENNIE,1079983207,https://www.youtube.com/watch?v=b73BI9eUkjM
8,BLACKPINK - ‘Pink Venom’ M\/V,Music Video,BLACKPINK,1066568014,https://www.youtube.com/watch?v=gQlMMD8auMs
9,BLACKPINK - 'Ice Cream (with Selena Gomez)' M\/V,Music Video,BLACKPINK,999149922,https://www.youtube.com/watch?v=vRXZj0DzXIA

#### **Top 10 Videos with the Highest Number of Likes**

In [21]:
latest_like_per_video = df.drop_duplicates(subset='id', keep='last')
top_10_liked_videos = latest_like_per_video.nlargest(10, 'likeCount').reset_index()
top_10_liked_videos['link'] = f'https://www.youtube.com/watch?v=' + top_10_viewed_videos['id']
print("Top 10 Videos with the Highest Number of Likes:")
display(top_10_liked_videos[['title', 'kind','artist','likeCount','link']])

Top 10 Videos with the Highest Number of Likes:

,title,kind,artist,likeCount,link
0,BLACKPINK - 'Kill This Love' M\/V,Music Video,BLACKPINK,26549714,https://www.youtube.com/watch?v=IHNzOHi8sJs
1,BLACKPINK - 'How You Like That' M\/V,Music Video,BLACKPINK,25252485,https://www.youtube.com/watch?v=2S24-y0Ij3Y
2,BLACKPINK - ‘뚜두뚜두 (DDU-DU DDU-DU)’ M\/V,Music Video,BLACKPINK,24738754,https://www.youtube.com/watch?v=32si5cfrCNc
3,BLACKPINK - 'Ice Cream (with Selena Gomez)' M\/V,Music Video,BLACKPINK,20523467,https://www.youtube.com/watch?v=bwmSjveL3Lc
4,BLACKPINK - 'How You Like That' DANCE PERFORMA...,Dance Practice Video,BLACKPINK,19991556,https://www.youtube.com/watch?v=Amq-qlqbjYA
5,LISA - 'LALISA' M\/V,Music Video,LISA,17716767,https://www.youtube.com/watch?v=ioNng23DkIM
6,BLACKPINK - ‘Pink Venom’ M\/V,Music Video,BLACKPINK,17486795,https://www.youtube.com/watch?v=dNCWe_6HAM8
7,BLACKPINK - '붐바야 (BOOMBAYAH)' M\/V,Music Video,BLACKPINK,17424419,https://www.youtube.com/watch?v=b73BI9eUkjM
8,BLACKPINK - 'Lovesick Girls' M\/V,Music Video,BLACKPINK,16143145,https://www.youtube.com/watch?v=gQlMMD8auMs
9,LISA - 'MONEY' EXCLUSIVE PERFORMANCE VIDEO,Performance,LISA,15461048,https://www.youtube.com/watch?v=vRXZj0DzXIA

#### **Top 10 Videos with the Highest Number of Comments**

In [22]:
latest_cmt_per_video = df.drop_duplicates(subset='id', keep='last')
top_10_cmt_videos = latest_cmt_per_video.nlargest(10, 'commentCount').reset_index()
top_10_cmt_videos['link'] = f'https://www.youtube.com/watch?v=' + top_10_viewed_videos['id']
print("Top 10 Videos with the Highest Number of Comments:")
display(top_10_cmt_videos[['title', 'kind','artist','commentCount','link']])

Top 10 Videos with the Highest Number of Comments:

,title,kind,artist,commentCount,link
0,BLACKPINK - 'How You Like That' M\/V,Music Video,BLACKPINK,4995508,https://www.youtube.com/watch?v=IHNzOHi8sJs
1,BLACKPINK - ‘Pink Venom’ M\/V,Music Video,BLACKPINK,3462650,https://www.youtube.com/watch?v=2S24-y0Ij3Y
2,JENNIE - 'SOLO' M\/V,Music Video,JENNIE,3325650,https://www.youtube.com/watch?v=32si5cfrCNc
3,BLACKPINK - ‘뚜두뚜두 (DDU-DU DDU-DU)’ M\/V,Music Video,BLACKPINK,3257369,https://www.youtube.com/watch?v=bwmSjveL3Lc
4,BLACKPINK - 'Ice Cream (with Selena Gomez)' M\/V,Music Video,BLACKPINK,3020580,https://www.youtube.com/watch?v=Amq-qlqbjYA
5,LISA - 'LALISA' M\/V,Music Video,LISA,2775320,https://www.youtube.com/watch?v=ioNng23DkIM
6,ROSÉ - 'On The Ground' M\/V,Music Video,ROSÉ,2556806,https://www.youtube.com/watch?v=dNCWe_6HAM8
7,BLACKPINK - 'Kill This Love' M\/V,Music Video,BLACKPINK,2502958,https://www.youtube.com/watch?v=b73BI9eUkjM
8,BLACKPINK - ‘Shut Down’ M\/V,Music Video,BLACKPINK,2074188,https://www.youtube.com/watch?v=gQlMMD8auMs
9,BLACKPINK - 'Lovesick Girls' M\/V,Music Video,BLACKPINK,2021172,https://www.youtube.com/watch?v=vRXZj0DzXIA

#### **Views Growth in 24 Hours:**

In [23]:
latest_date_data = df[df['date'] == df['date'].max()]
previous_date_data = df[df['date'] == (df['date'].max() - pd.Timedelta(days=1))]
merged_data = pd.merge(latest_date_data, previous_date_data, on=['title'], suffixes=('_latest', '_previous'), how='inner')
merged_data['viewCount_increase'] = merged_data['viewCount_latest'] - merged_data['viewCount_previous']

top_10_increase_videos = merged_data.nlargest(10, 'viewCount_increase').reset_index()
top_10_increase_videos['link'] = f'https://www.youtube.com/watch?v=' + top_10_increase_videos['id_latest']
print("Top 10 Videos with the Highest Increase in Views from the Previous Day:")
display(top_10_increase_videos[['title','date_latest','viewCount_increase','viewCount_latest','link']])

Top 10 Videos with the Highest Increase in Views from the Previous Day:

,title,date_latest,viewCount_increase,viewCount_latest,link
0,BLACKPINK - 'How You Like That' DANCE PERFORMA...,2026-04-09,417729,1979833234,https://www.youtube.com/watch?v=32si5cfrCNc
1,BLACKPINK - ‘뛰어(JUMP)’ M\/V,2026-04-09,407956,369348177,https://www.youtube.com/watch?v=CgCVZdcKcqY
2,BLACKPINK - ‘GO’ M\/V,2026-04-09,365199,66557683,https://www.youtube.com/watch?v=2GJfWMYCWY0
3,LISA - 'MONEY' EXCLUSIVE PERFORMANCE VIDEO,2026-04-09,245539,1202262949,https://www.youtube.com/watch?v=dNCWe_6HAM8
4,BLACKPINK - 'Kill This Love' M\/V,2026-04-09,242259,2200051175,https://www.youtube.com/watch?v=2S24-y0Ij3Y
5,BLACKPINK - ‘Pink Venom’ M\/V,2026-04-09,203063,1066568014,https://www.youtube.com/watch?v=gQlMMD8auMs
6,BLACKPINK - '붐바야 (BOOMBAYAH)' M\/V,2026-04-09,193930,1866736665,https://www.youtube.com/watch?v=bwmSjveL3Lc
7,BLACKPINK - ‘Shut Down’ M\/V,2026-04-09,177025,797240558,https://www.youtube.com/watch?v=POe9SOEKotk
8,BLACKPINK - ‘뚜두뚜두 (DDU-DU DDU-DU)’ M\/V,2026-04-09,174676,2380623358,https://www.youtube.com/watch?v=IHNzOHi8sJs
9,BLACKPINK - '마지막처럼 (AS IF IT'S YOUR LAST)' M\/V,2026-04-09,166240,1512166696,https://www.youtube.com/watch?v=Amq-qlqbjYA